spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce
    username: root
    password: 12345678
  jpa:
    hibernate:
      ddl-auto: create
management:
  endpoints:
      exposure:
        include: "*"
  info:
    env:
      enabled: true